### ISSUE TITLE
What's this theme?

### ISSUE THREAD

**Issue by axisdos** [EngageWP/dashing#1]
Hey EngageWP, I've been following your blog since a few months ago. This should be your new theme hah? What does it do and is it done yet?

**Comment by EngageWP** [comment]
Hey, Daymond. Glad to hear you like the blog! 

I actually just created this repo for a Genesis child theme I'm starting to build. I decided I want to build something new for EngageWP and this will be it. Right now, it's just a copy of the Genesis sample child theme. I'm still toying with ideas but I want to give it a dashboard-like appearance, hence the name.

**Comment by axisdos** [comment]
Dashboard-like appearance hmmm.. (WP Admin Dashboard?)

**Comment by EngageWP** [comment]
Sort of but not totally. I guess the best way to describe it would be in terms of displaying content. Rather than maintaining a traditional blog "look", I'm thinking about presenting things like post meta, social links, author info, etc., in a "widgetized" manner and maybe even use a vertical navigation menu and tabs to access different things, like comments. Basically, it will be a very modular look, similar to a dashboard.

Hopefully that makes sense! :-)

**Comment by axisdos** [comment]
No that makes sense lol. Can't wait to see it man. Keep up the good work!
